modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
    modId="onurkneeentity"
    version="${file.jarVersion}"
    isplayName="On Your Knee Entity"
    authors="Semenzhi"
    description='''${mod_description}'''

[[mixins]]
    config="okt.mixins.json"

[[dependencies.onurkneeentity]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.onurkneeentity]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4,)"
    ordering="NONE"
    side="BOTH"
