modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
    modId="onurkneeentity"
    version="${mod_version}"
    displayName="On Your Knee Entity"
    authors="Semenzhi"
    description='''${mod_description}'''

[[mixins]]
    config="okt.mixins.json"

[[dependencies.onurkneeentity]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.onurkneeentity]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
